export const DEFAULT_TASK_CATEGORIES = [
  {
    name: "Income",
    icon: "wallet-outline",
    color: "#FDE68A",
    subCategories: [
      { name: "Salary" },
      { name: "Freelance Income" },
      { name: "Business Income" },
      { name: "Daily Wages" },
      { name: "Overtime Pay" },
      { name: "Bonus" },
      { name: "Commission" },
      { name: "Rental Income" },
      { name: "Farming Income" },
      { name: "Interest Income" },
      { name: "Dividends" },
      { name: "Pension" },
    ],
  },
  {
    name: "Groceries & Daily Needs",
    icon: "cart-outline",
    color: "#BBF7D0",
    subCategories: [
      { name: "Vegetables" },
      { name: "Fruits" },
      { name: "Dairy Products" },
      { name: "Meat & Fish" },
      { name: "Rice & Grains" },
      { name: "Cooking Oil" },
      { name: "Snacks" },
      { name: "Beverages" },
      { name: "Cleaning Supplies" },
      { name: "Toiletries" },
      { name: "Baby Products" },
    ],
  },
  {
    name: "Household",
    icon: "home-outline",
    color: "#BAE6FD",
    subCategories: [
      { name: "House Rent" },
      { name: "House Maintenance" },
      { name: "Furniture" },
      { name: "Appliances" },
      { name: "Repairs" },
      { name: "Painting" },
      { name: "Plumber" },
      { name: "Electrician" },
      { name: "Carpenter" },
      { name: "House Help Salary" },
      { name: "Cook Salary" },
      { name: "Driver Salary" },
    ],
  },
  {
    name: "Bills & Utilities",
    icon: "flash-outline",
    color: "#C7D2FE",
    subCategories: [
      { name: "Electricity Bill" },
      { name: "Water Bill" },
      { name: "Gas Bill" },
      { name: "Internet Bill" },
      { name: "Mobile Recharge" },
      { name: "DTH / TV Subscription" },
      { name: "Maintenance Charges" },
      { name: "Garbage Collection Fee" },
    ],
  },
  {
    name: "Vehicle",
    icon: "car-outline",
    color: "#FBCFE8",
    subCategories: [
      { name: "Fuel" },
      { name: "Service & Maintenance" },
      { name: "Vehicle Repairs" },
      { name: "Vehicle Insurance" },
      { name: "Pollution Certificate" },
      { name: "Parking Fees" },
      { name: "Toll Charges" },
      { name: "Vehicle Loan EMI" },
    ],
  },
  {
    name: "Finance & Loans",
    icon: "cash-outline",
    color: "#DDD6FE",
    subCategories: [
      { name: "Home Loan EMI" },
      { name: "Personal Loan EMI" },
      { name: "Credit Card Bill" },
      { name: "Insurance Premium" },
      { name: "Medical Insurance" },
      { name: "Life Insurance" },
      { name: "Investments" },
      { name: "Savings Deposit" },
      { name: "Mutual Funds" },
      { name: "Stock Market" },
      { name: "Taxes" },
    ],
  },
  {
    name: "Health",
    icon: "medkit-outline",
    color: "#FECACA",
    subCategories: [
      { name: "Doctor Consultation" },
      { name: "Medicines" },
      { name: "Hospital Charges" },
      { name: "Lab Tests" },
      { name: "Gym Membership" },
      { name: "Health Checkup" },
    ],
  },
  {
    name: "Education",
    icon: "school-outline",
    color: "#BFDBFE",
    subCategories: [
      { name: "School Fees" },
      { name: "College Fees" },
      { name: "Books" },
      { name: "Online Courses" },
      { name: "Coaching Classes" },
    ],
  },
  {
    name: "Shopping",
    icon: "bag-outline",
    color: "#FDE2E4",
    subCategories: [
      { name: "Clothing" },
      { name: "Electronics" },
      { name: "Home Decor" },
      { name: "Gifts" },
      { name: "Online Orders" },
    ],
  },
  {
    name: "Family & Personal",
    icon: "people-outline",
    color: "#D9F99D",
    subCategories: [
      { name: "Family Events" },
      { name: "Marriage Expenses" },
      { name: "Birthday Celebration" },
      { name: "Travel" },
      { name: "Vacation" },
      { name: "Entertainment" },
      { name: "Dining Out" },
    ],
  },
  // {
  //   name: "Farming & Agriculture",
  //   icon: "leaf-outline",
  //   color: "#A7F3D0",
  //   subCategories: [
  //     { name: "Seeds" },
  //     { name: "Fertilizers" },
  //     { name: "Pesticides" },
  //     { name: "Labour Charges" },
  //     { name: "Equipment Purchase" },
  //     { name: "Water Irrigation" },
  //   ],
  // },
  {
    name: "Emergency",
    icon: "warning-outline",
    color: "#FCA5A5",
    subCategories: [
      { name: "Medical Emergency" },
      { name: "Vehicle Breakdown" },
      { name: "Unexpected Repairs" },
      { name: "Legal Fees" },
    ],
  },
];